version: '3.8'


networks:
  freeport:
    external: true
services:
  btcwallet:
    container_name: freeport-btc
    image: freeport/freeport-btc
    restart: on-failure
    build:
        context: ./
        dockerfile: ./Dockerfile
    volumes:
        - ./:/app
        - freeport_wallet_btc:/home/droid/freeport/data
    ports:
      - '5085:5085'
    networks:
      - freeport
volumes:

  freeport_wallet_btc:
  db:
    driver: local
